// packages/examples/caching/src/Results/Results.tsx
import { type FC } from "react";
import { useStanRefresh, useStanValueAsync } from "@rkrupinski/stan/react";

import { swSearch } from "./state";

import styles from "./Results.module.scss";

export type ResultsProps = {
  phrase: string;
};

export const Results: FC<ResultsProps> = ({ phrase }) => {
  const data = useStanValueAsync(swSearch(phrase));
  const refresh = useStanRefresh(swSearch(phrase));

  return (
    <div className={styles.resultsContainer}>
      {data.type === "loading" && (
        <p className={styles.text}>Loading&hellip;</p>
      )}
      {data.type === "error" && (
        <>
          <p className={styles.text}>Nope: {data.reason}</p>
          <button onClick={refresh}>Try again</button>
        </>
      )}
      {data.type === "ready" && (
        <>
          {data.value.result.length ? (
            <ul className={styles.results}>
              {data.value.result
                .slice(0, 5)
                .map(({ properties: { name, url } }) => (
                  <li key={url} className={styles.result}>
                    <a href={url} target="_blank" rel="noopener noreferrer">
                      {name}
                    </a>
                  </li>
                ))}
            </ul>
          ) : (
            <p className={styles.text}>No results</p>
          )}
        </>
      )}
    </div>
  );
};

// packages/examples/vue-caching/src/Results.vue
<script setup lang="ts">
import { useStanValueAsync, useStanRefresh } from "@rkrupinski/stan/vue";

import { swSearch } from "./state";

const props = defineProps<{ phrase: string }>();

const data = useStanValueAsync(swSearch(props.phrase));
const refresh = useStanRefresh(swSearch(props.phrase));
</script>

<template>
  <div class="resultsContainer">
    <p v-if="data.type === 'loading'" class="text">Loading&hellip;</p>
    <template v-else-if="data.type === 'error'">
      <p class="text">{{ String(data.reason) }}</p>
      <button @click="refresh">Try again</button>
    </template>
    <template v-else>
      <ul v-if="data.value.result.length" class="results">
        <li
          v-for="{ properties: { name, url } } in data.value.result.slice(0, 5)"
          :key="url"
          class="result"
        >
          <a :href="url" target="_blank" rel="noopener noreferrer">{{ name }}</a>
        </li>
      </ul>
      <p v-else class="text">No results</p>
    </template>
  </div>
</template>

<style scoped>
.resultsContainer {
  width: 250px;
  padding: 0.25rem;
  position: absolute;
  left: 0;
  top: calc(100% + 2px);
  border: 1px dotted #000;
  border-radius: 0.25rem;
  background: #fff;
}

.results {
  list-style: none;
  padding: 0;
  margin: 0;
}

.result:not(:first-child)::before {
  content: "";
  display: block;
  margin: 0.25rem 0;
  border-top: 1px dotted #000;
}

.text {
  margin: 0;
}
</style>
